export const environment = {
  firebase: {
    projectId: 'davesa',
    appId: '1:285127898951:web:1a00713f3622d33a093e62',
    storageBucket: 'davesa.appspot.com',
    locationId: 'us-central',
    apiKey: 'AIzaSyAqGmcYp0VXI1nQx-fpBi9v3dwB7U8uzHs',
    authDomain: 'davesa.firebaseapp.com',
    messagingSenderId: '285127898951',
    measurementId: 'G-WVN96DWE6Q',
  },
  LOCAL_STORAGE_KEY: 'DAVESA01-1730-0000-0000-encrypt00000',
  production: false,
  API_URL: 'https://stg-api.davesa.com/api/v1/',
  PLACES_API_URL: 'https://places.googleapis.com/v1/places:autocomplete',
  // SOCKET_URL: 'https://stg-api.davesa.com/',
  GLOBAL_SOCKET_URL: 'https://stg-api.davesa.com/global-notification',
  SUBJECT_VISIT_SOCKET_URL: 'https://stg-api.davesa.com/subject-visit-chat',
  STUDY_ESOURCE_SOCKET_URL: 'https://stg-api.davesa.com/study-esource-chat',
  GOOGLE_DOCS_URL: 'https://storage.googleapis.com/davesa-documents-stag',
  GOOGLE_CLIENT_ID: '166152712143-l8mqghdju0aocg6mdi2li123lto34oa9.apps.googleusercontent.com',
};
