/* eslint-disable */
export const sponsors = [
    {
        id: 1,
        oid: '00000001-0000-0000-0000-000000000000',
        name: 'Rare Thyroid Therapeutics',
        website: 'http://www.rarethyroid.com/',
        email: '',
        street_1: '',
        street_2: '',
        mobile_phone: '',
        phone_phone: '',
        country_name: '',
        address: 'Klara Norra Kyrkogata 26, Stockholm County, Sweden',
        state_id: '',
        country_id: 1,
        city_id: 2,
        state: '',
        country: '',
        city: '',
        country_code: 1,
        type: '',
        zip: '',
        created_by: 1,
        updated_by: 1,
        stateName: '',
        countryName: '',
        cityName: '',
        created_at: '2019-05-24T03:55:38.969Z'      
    },
    {
        id: 2,
        oid: '00000002-0000-0000-0000-000000000000',
        name: 'Amgen Inc.',
        website: 'https://www.amgen.com',
        email: '',
        street_1: '',
        street_2: '',
        mobile_phone: '',
        phone_phone: '',
        country_name: '',
        address: 'One Amgen Center Drive Thousand Oaks, California 91320 USA',
        state_id: '',
        country_id: 1,
        city_id: 2,
        state: '',
        country: '',
        city: '',
        country_code: 1,
        type: '',
        zip: '',
        created_by: 1,
        updated_by: 1,
        stateName: '',
        countryName: '',
        cityName: '',
        created_at: '2019-05-24T03:55:38.969Z'      
    },
    {
        id: 3,
        oid: '00000003-0000-0000-0000-000000000000',
        name: 'Theravance Biopharma Ireland Limited',
        website: 'https://www.theravance.com',
        email: '',
        street_1: '',
        street_2: '',
        mobile_phone: '',
        phone_phone: '',
        country_name: '',
        address: 'Ten Earlsfort Terrace, Dublin 2 Dublin, Ireland 30329',
        state_id: '',
        country_id: 1,
        city_id: 2,
        state: '',
        country: '',
        city: '',
        country_code: 1,
        type: '',
        zip: '',
        created_by: 1,
        updated_by: 1,
        stateName: '',
        countryName: '',
        cityName: '',
        created_at: '2019-05-24T03:55:38.969Z'      
    },
    {
        id: 4,
        oid: '00000004-0000-0000-0000-000000000000',
        name: 'Dyne Therapeutics, Inc',
        website: 'https://www.dyne-tx.com/',
        email: '',
        street_1: '',
        street_2: '',
        mobile_phone: '',
        phone_phone: '',
        country_name: '',
        address: '1560 Trapelo Rd Waltham, Massachusetts 02451 USA',
        state_id: '',
        country_id: 1,
        city_id: 2,
        state: '',
        country: '',
        city: '',
        country_code: 1,
        type: '',
        zip: '',
        created_by: 1,
        updated_by: 1,
        stateName: '',
        countryName: '',
        cityName: '',
        created_at: '2019-05-24T03:55:38.969Z'      
    },
]
